version: '3.1'

services:
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=wheelscare
      - POSTGRES_DB=wheelscare
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  dbdata:
